### PR TITLE
refactor/naive bayes with tensors

### PR DESCRIPTION
**Pull request by benjaminmcdonald**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Rewrite of GaussianNB with Tensorflow support. 

The PR also introduces:

- Iterator implementation for `predict`
- Tensorflow Linear Algebra refactoring
- Updating the doc-processor to support native types such as `IterableIteration`

### CODE REVIEW

**Comment by JasonShin** [comment]
Hey, could you help me fix this issue?

I cloned your repository and ran `yarn` to install npm modules then `yarn test`, but I am getting below error

```
src/lib/naive_bayes/multinomial.ts:84:14 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '(<U>(callbackfn: (value: ReadonlyArray<number>, index: number, array: ReadonlyArray<ReadonlyArray...' has no compatible call signatures.

84       return X.map((x):T => this.singlePredict(x));
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


src/lib/naive_bayes/multinomial.ts:167:30 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '{ (callbackfn: (previousValue: number, currentValue: number, currentIndex: number, array: Readonl...' has no compatible call signatures.

167       productReducedRow.push(rowFrequencyCount.reduce((s, c) => s + c, 0));
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by JasonShin** [comment]
Ok, I resolved the error from doc processor

```
Using TypeScript 2.7.2 from /home/jason/Desktop/kalimdorjs/node_modules/typedoc/node_modules/typescript/lib
To generate markdown please set option --theme markdown

JSON written to /home/jason/Desktop/kalimdorjs/docs/docs.json

/home/jason/Desktop/kalimdorjs/docs/processor/index.js:274
            if (foundRef.kindString === consts.refKindInterface) {
                         ^

TypeError: Cannot read property 'kindString' of null
    at /home/jason/Desktop/kalimdorjs/docs/processor/index.js:274:26
    at arrayReduce (/home/jason/Desktop/kalimdorjs/node_modules/lodash/lodash.js:683:21)
    at Function.reduce (/home/jason/Desktop/kalimdorjs/node_modules/lodash/lodash.js:9683:14)
```

You were getting this error due to introducing a TS Native Interface `IterableIterator`. So far in Kalimdor, we've only been using custom defined Interfaces such as `StrNumDict` or `InterfaceFitModel`. The difference between `custom` and `native` interface is that the former gives you an ID as a reference, which you can use it to find its definition, on the other hand, the latter does not expose an ID. Here are examples:

Custom Interface
```
{
					"id": 1130,
					"name": "InterfaceFitModel",
					"kind": 256,
					"kindString": "Interface",
					"flags": {},
					"typeParameter": [
						{
							"id": 1131,
							"name": "T",
							"kind": 131072,
							"kindString": "Type parameter",
							"flags": {}
						}
					],
					"children": [
						{
							"id": 1132
```

^^ has an ID that we can use to reference its definition within `docs.json`. However, a native interface such as `IterableIteration` does not have an ID because it's a native type. 

Anyways, thanks @benjaminmcdonald  for helping us improving the documentation processor =) !!

**Comment by benjaminmcdonald** [comment]
Update the branch with added support for constraint in doc types added multinomial naive bayes. This with your above patch fixed the issue with the document generation. yarn test now completes

**Comment by JasonShin** [comment]
I am going to write some TODOs for myself here

TODO:
(?) Removing excessive comments
(?) Add exception tests for MultinomialNB
(?) Add real data tests using Iris for MultinomialNB
(?) modelState can be just class fields
(?) export MultinomialNB in index.ts
(?) Add integration tests
(?) refactor isMatrix usage to tensor_ops.ts APIs
(?) Running yarn doc prints
```
[ { type: 'reference',
    name: 'IterableIterator',
    typeArguments: [ [Object] ] } ]
[ { type: 'typeParameter',
    name: 'T',
    constraint: { type: 'union', types: [Array] } } ]
[ { type: 'reference',
    name: 'IterableIterator',
    typeArguments: [ [Object] ] } ]
```

to the screen. Remove the console logs.
(?) Running the MultinomialNB unit tests prints

```

  console.log node_modules/@tensorflow/tfjs-core/dist/ops/array_ops.js:500
    Tensor
        [[-0.8873032, -0.5306282],
         [-0.6931472, -0.6931472],
         [-0.4700036, -0.9808292]]

  console.log node_modules/@tensorflow/tfjs-core/dist/ops/array_ops.js:500
    Tensor
        [-1.0986123, -1.0986123, -1.0986123]
```

on the screen

**Comment by JasonShin** [comment]
I propose we exclude 

```

  /**
   * @param  {IterableIterator<IterableIterator<number>>} X
   * @returns IterableIterator
   */
  public *predictIterator(
    X: IterableIterator<IterableIterator<number>>
  ): IterableIterator<T> {
    for (const x of X) {
      yield this.singlePredict([...x]);
    }
  }
```
from this PR. I think it's best to introduce this feature in a separate PR that implements it globally throughout the existing models.

**Comment by JasonShin** [comment]
I think this PR Is fine to be merged now!! GREAT WORK and thanks for your second contributions @benjaminmcdonald !!!

I will address the documentation issue that I describe in https://github.com/kalimdorjs/kalimdorjs/issues/161 in a separate branch.

**Pull request merged**
